### ISSUE TITLE
clone Organization

### ISSUE THREAD

**Issue by jazzz88** [oxosolutions/adminpie#4]
Create new group=>>Create new Organization =>> when we copy oganization with clone.copy organization cannt be login

**Comment by paljinderSingh13** [comment]
auto organization login  relate to mr rahul

**Comment by sgssandhu** [comment]
The issue is related to user activation from group. The user added to any organization should be activated in the group by default.

**Comment by rahulsharma841990** [comment]
Duplicate of #9

**Comment by jazzz88** [comment]
Create new group=>>Create new Organization =>> when we copy oganization with clone.copy organization cannt be login
still not working

**Comment by rahulsharma841990** [comment]
Clone organization bug fixed, kindly check and confirm.

Thanks

**Comment by jazzz88** [comment]
Its Working Now..Thanks
